### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by thmsklngr** [hotgluexyz/gluestick#1]
Hi,

just found an interesting article promoting this library, but unfortunately I can't find any documentation on how to use it. Will it be added (hopefully soon)?

Regards, Thomas

**Comment by hsyyid** [comment]
Yes! We plan to add the full documentation this week - thank you!

**Comment by hsyyid** [comment]
We’ve posted barebones docs onto the Wiki page. I’ll be improving this with some better examples this week so I’ll leave this issue open for now.

https://github.com/hotgluexyz/gluestick/wiki

**Comment by hsyyid** [comment]
Initial docs have been updated on the [Wiki](https://github.com/hotgluexyz/gluestick/wiki). Going to close this issue!
